'use client';
import {useState} from 'react';
import {Target,BrainCircuit,Plus,Pencil,Trash2,ArrowRight,PiggyBank,CalendarDays,Search,Wallet,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Data,Entry,Reserve,money,sum,today,addMonths,validate} from '@/lib/finance';
import {contribute,goalPace,planMoney,spending} from '@/lib/planning';

const dateLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('pt-BR');
export default function PlanningPanel({data,scope,account,days,busy,save,show,onPay}:{data:Data;scope:string;account:string;days:number;busy:boolean;save:(d:Data)=>Promise<boolean>;show:(t:string,e:Entry[])=>void;onPay:(e:Entry)=>void}){
 const [tab,setTab]=useState('plan'),[mode,setMode]=useState(''),[form,setForm]=useState<any>({}),[error,setError]=useState(''),[deleting,setDeleting]=useState<Reserve|null>(null),[budget,setBudget]=useState(''),[query,setQuery]=useState('');
 const plan=planMoney(data,scope,account,days),history=spending(data,scope,account);
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const searched=history.expenses.filter(e=>normalize(e.description+' '+(e.origin||'')+' '+e.category).includes(normalize(query)));
 const customBudget=budget===''?null:Math.round(Number(budget)*100),foodSavings=customBudget===null?0:Math.max(0,history.foodWeek-customBudget);
 function openGoal(goal?:Reserve){setError('');setMode('goal');setForm(goal?{...goal,goal:goal.goal/100}:{name:'',account:account||plan.accounts[0]?.id||'',goal:'',amount:0,targetDate:addMonths(today(),6),priority:2,notes:''})}
 function openMoney(goal:Reserve,release=false,amount?:number){setError('');setMode(release?'release':'contribute');setForm({...goal,value:amount?amount/100:'',horizon:days})}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{
  let next=structuredClone(data);
  if(mode==='goal'){
   const old=next.reserves.find(r=>r.id===form.id);const target=Math.round(Number(form.goal)*100);
   if(old&&old.amount>0&&old.account!==form.account)throw Error('Libere o valor já reservado antes de mudar a conta da meta.');
   const goal:Reserve={id:form.id||crypto.randomUUID(),name:form.name.trim(),account:form.account,goal:target,amount:old?.amount||0,isGoal:true,targetDate:form.targetDate,priority:Number(form.priority),notes:form.notes};
   next.reserves=next.reserves.filter(r=>r.id!==goal.id).concat(goal);
  }else{
   const value=Math.round(Number(form.value)*100),goal=next.reserves.find(r=>r.id===form.id);
   if(!goal)throw Error('Meta não encontrada.');
   if(mode==='release'){if(!Number.isSafeInteger(value)||value<=0||value>goal.amount)throw Error('Informe um valor até o total reservado.');goal.amount-=value;}
   else next=contribute(next,form.id,value,days);
  }
  validate(next);if(await save(next))setMode('');
 }catch(e:any){setError(e.message)}}
 async function removeGoal(){try{if(!deleting)return;await save({...data,reserves:data.reserves.filter(r=>r.id!==deleting.id)});setDeleting(null)}catch(e:any){setError(e.message);setDeleting(null)}}
 const empty=<div className="empty"><Target size={30}/><strong>Um plano começa com um objetivo.</strong><span>Cadastre uma viagem, um carro ou outra conquista com valor e prazo.</span><button className="btn primary" disabled={!plan.accounts.length} onClick={()=>openGoal()}>Criar minha primeira meta</button></div>;
 return <section className="planning-panel">
  <div className="section-title"><div><h2><BrainCircuit size={21}/> Planejamento inteligente</h2><p>Análise automática dos seus registros · valores recalculados a cada alteração</p></div><button className="btn primary" disabled={!plan.accounts.length} onClick={()=>openGoal()}><Plus size={17}/>Nova meta</button></div>
  <Tabs value={tab} onValueChange={setTab}><TabsList className="planning-tabs"><TabsTrigger value="plan">Plano de ação</TabsTrigger><TabsTrigger value="goals">Metas e sonhos</TabsTrigger><TabsTrigger value="spending">Gastos do dia a dia</TabsTrigger></TabsList></Tabs>
  {error&&!mode&&<div role="alert" className="error">{error}</div>}
  {tab==='plan'&&<>
   <div className="planning-hero"><div><span className="eyebrow">MARGEM PARA GUARDAR AGORA</span><strong>{money(plan.capacity)}</strong><p>Após proteger reservas, compromissos e uma estimativa da rotina pelos próximos {days} dias.</p></div><div className="planning-formula"><span>Dinheiro em contas <b>{money(plan.current)}</b></span><span>Reservas existentes <b>− {money(plan.reserved)}</b></span><span>Contas e faturas até {dateLabel(plan.until)} <b>− {money(plan.committed)}</b></span><span>Estimativa de novos gastos cotidianos <b>− {money(plan.routine)}</b></span></div></div>
   <p className="planning-note"><Info size={16}/>Recebimentos previstos não financiam estas sugestões. A margem é calculada por conta; contas com falta de dinheiro aparecem abaixo.</p>
   {plan.accounts.some(a=>a.coverage<14)&&<div className="planning-warning">Histórico ainda curto em uma ou mais contas. A estimativa usa os dias registrados (até 28 dias) e pode não refletir toda a sua rotina. Confira despesas que ainda não foram cadastradas antes de reservar dinheiro.</div>}
   {plan.gap<0&&<div className="planning-warning"><strong>Priorize cobrir {money(-plan.gap)} nas contas abaixo.</strong><p>O cálculo inclui os compromissos registrados e a rotina estimada. Revise os vencimentos ou transfira dinheiro entre contas do mesmo orçamento antes de criar novas reservas.</p></div>}
   <div className="planning-accounts">{plan.accounts.map(a=><div className="panel" key={a.id}><div className="section-title"><h2>{a.name}</h2><span className="badge gray">{a.scope}</span></div><strong className="account-value">{money(a.gap<0?-a.gap:a.capacity)}</strong><p>{a.gap<0?'Falta para cobrir o plano':'Margem para guardar nesta conta'}</p><div className="health-line"><span>Saldo existente</span><b>{money(a.current)}</b></div><div className="health-line"><span>Reservas + compromissos</span><b>{money(a.reserved+a.committed)}</b></div><div className="health-line"><span>Rotina estimada em {days} dias</span><b>{money(a.routine)}</b></div><button className="text-link" onClick={()=>show('Compromissos · '+a.name,a.bills)}>Conferir contas e faturas <ArrowRight size={15}/></button></div>)}</div>
   <div className="panel"><div className="section-title"><h2>Quanto destinar a cada objetivo</h2><span className="badge gray">Por prioridade e prazo</span></div><p className="muted">As sugestões abaixo dividem o dinheiro disponível: a mesma quantia não é prometida para duas metas.</p>{plan.allocations.length?plan.allocations.map(({goal,pace,amount,account:a})=><div className="planning-action" key={goal.id}><span className="small-icon purple"><Target size={20}/></span><div><strong>{amount>0?`Guarde ${money(amount)} para ${goal.name}`:`Aguarde para guardar para ${goal.name}`}</strong><p>{a.name} · faltam {money(pace.remaining)}. Ritmo necessário: {money(pace.monthly)}/mês ou {money(pace.weekly)}/semana.</p><small>{amount>0?`Sugestão para o horizonte de ${days} dias, limitada ao saldo já existente e à prioridade da meta.`:pace.remaining===0?'Meta concluída.':`A margem da conta está comprometida ou foi destinada a metas prioritárias. Revise o prazo ou o orçamento.`}</small></div><button className="btn" disabled={!amount||busy} onClick={()=>openMoney(goal,false,amount)}>Guardar</button></div>):empty}</div>
   <div className="panel"><div className="section-title"><h2>Vale antecipar uma conta?</h2><CalendarDays size={20}/></div><p className="muted">Pagar antes muda o momento da saída; sozinho, isso não aumenta o dinheiro disponível. Considere antecipar para organizar vencimentos ou se o credor oferecer desconto. Você precisa confirmar o pagamento real.</p>{plan.prepay.length?plan.prepay.map(e=><div className="planning-action" key={e.id}><span className="small-icon purple"><CalendarDays size={19}/></span><div><strong>{e.description} · {money(e.amount)}</strong><p>Vence em {dateLabel(e.date)}. Este compromisso já está descontado no plano da conta {data.accounts.find(a=>a.id===e.account)?.name}.</p><small>Você pode separar mentalmente esse valor ou pagar antes após conferir as condições com o credor. Não crie outra reserva para essa mesma obrigação.</small></div><button className="btn" onClick={()=>onPay(e)}>Registrar pagamento</button></div>):<p className="planning-note">Não há uma conta futura elegível para antecipação neste horizonte. Priorize atrasados e vencimentos próximos.</p>}</div>
  </>}
  {tab==='goals'&&<>{!plan.allocations.length?empty:<div className="planning-goals">{plan.allocations.map(({goal,pace,amount})=><div className="panel goal-card" key={goal.id}><div className="section-title"><span className="small-icon purple"><Target size={21}/></span><span className="badge gray">{['','Alta prioridade','Prioridade média','Baixa prioridade'][goal.priority||2]}</span></div><h2>{goal.name}</h2><p>{data.accounts.find(a=>a.id===goal.account)?.name} · até {dateLabel(goal.targetDate!)}</p><div className="goal-amount"><strong>{money(goal.amount)}</strong><span>de {money(goal.goal)}</span></div><div className="progress"><i style={{width:pace.progress+'%'}}/></div><p>{pace.progress.toFixed(0)}% concluído · faltam {money(pace.remaining)}</p><div className="health-line"><span>Ritmo mensal necessário</span><b>{money(pace.monthly)}</b></div><div className="health-line"><span>Ritmo semanal necessário</span><b>{money(pace.weekly)}</b></div><p className="muted">{pace.remaining===0?'Objetivo alcançado!':pace.late?'O prazo passou. Edite a data para recalcular seu plano.':`Para ${dateLabel(goal.targetDate!)}. O ritmo é uma necessidade da meta, não uma promessa de renda futura.`}</p>{goal.notes&&<p className="muted">{goal.notes}</p>}<div className="goal-buttons"><button className="btn primary" disabled={busy||pace.remaining===0} onClick={()=>openMoney(goal,false,amount)}><PiggyBank size={16}/>Guardar</button><button className="btn" disabled={!goal.amount||busy} onClick={()=>openMoney(goal,true)}>Liberar valor</button></div><div className="card-footer"><button onClick={()=>openGoal(goal)}><Pencil size={15}/> Editar meta</button><button title="Excluir meta e liberar reserva" onClick={()=>setDeleting(goal)}><Trash2 size={16}/></button></div></div>)}</div>}<p className="planning-note"><Wallet size={17}/>O valor guardado entra nas reservas do Clareza e reduz o saldo livre. Ele permanece na conta bancária; nenhum dinheiro é movimentado automaticamente.</p></>}
  {tab==='spending'&&<>
   <div className="stats-grid three"><button className="stat" onClick={()=>show('Gastos nos últimos 7 dias',history.weekly[3].items)}><span>Últimos 7 dias</span><strong>{money(history.weekly[3].total)}</strong><small>Ver lançamentos</small></button><button className="stat" onClick={()=>show('Alimentação · 28 dias',history.food)}><span>Comida nos últimos 7 dias</span><strong>{money(history.foodWeek)}</strong><small>{money(sum(history.food,e=>e.amount))} nos últimos 28 dias</small></button><button className="stat" onClick={()=>show('Shopee · 28 dias',history.shopee)}><span>Shopee nos últimos 7 dias</span><strong>{money(history.shopeeWeek)}</strong><small>{money(sum(history.shopee,e=>e.amount))} nos últimos 28 dias</small></button></div>
   <div className="panel"><h2>Como suas semanas estão mudando</h2><div className="week-bars">{history.weekly.map(w=><button key={w.from} onClick={()=>show(w.label,w.items)}><span>{dateLabel(w.from)} — {dateLabel(w.to)}</span><div className="progress"><i style={{width:(w.total/Math.max(1,...history.weekly.map(x=>x.total))*100)+'%'}}/></div><b>{money(w.total)}</b></button>)}</div><p className="muted">Quatro períodos consecutivos de 7 dias. Compras de cartão entram pela data registrada; o pagamento da fatura não é contado como nova despesa.</p></div>
   <div className="two-col"><div className="panel"><h2>Uma direção para os gastos com comida</h2><p className="planning-copy">{history.foodWeek?`Você registrou ${money(history.foodWeek)} com alimentação nos últimos 7 dias. Compare quanto disso veio de delivery e refeições fora com um orçamento de mercado para a próxima semana.`:'Cadastre refeições, mercado e delivery para identificar seu padrão de alimentação.'}</p><label className="field"><span>Orçamento de alimentação para a próxima semana (R$)</span><input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Inclua mercado, refeições e delivery"/></label>{customBudget!==null&&<div className="simulation-result"><strong>{money(foodSavings)}</strong><p>Possível redução em uma semana se você gastar até {money(customBudget)}. Equivale a {money(foodSavings*4)} em quatro semanas mantendo o mesmo limite.</p></div>}<p className="muted">Simulação, não economia garantida. Use preços pesquisados por você e inclua o custo do mercado; o sistema não consulta preços externos.</p><button className="text-link" onClick={()=>show('Detalhes dos gastos com alimentação',history.food)}>Conferir alimentação <ArrowRight size={14}/></button></div><div className="panel"><h2>Compras por estabelecimento</h2><div className="search merchant-search"><Search size={18}/><input aria-label="Buscar estabelecimento" placeholder="Ex.: Shopee, iFood, mercado" value={query} onChange={e=>setQuery(e.target.value)}/></div><strong className="account-value">{money(sum(searched,e=>e.amount))}</strong><p>{searched.length} lançamentos encontrados nos últimos 28 dias.</p><button className="btn" onClick={()=>show(query?'Gastos · '+query:'Gastos · 28 dias',searched)}>Ver lançamentos</button><p className="muted">A identificação considera descrição, origem e categoria. Use o nome do estabelecimento ao cadastrar a compra.</p>{history.shopeeWeek>0&&<p className="planning-copy">Antes da próxima compra na Shopee, confira se ela cabe na margem para guardar e se adia alguma das suas metas.</p>}</div></div>
   <div className="panel"><h2>Gastos por categoria</h2>{history.groups.length?<div className="table-scroll"><table><thead><tr><th>Categoria</th><th>7 dias anteriores</th><th>Últimos 7 dias</th><th>Variação</th><th>28 dias</th></tr></thead><tbody>{history.groups.map(g=><tr key={g.name}><td><button className="text-link" onClick={()=>show(g.name,g.items)}>{g.name}</button></td><td>{money(g.previous)}</td><td>{money(g.current)}</td><td>{g.previous?`${g.current>=g.previous?'+':''}${((g.current-g.previous)/g.previous*100).toFixed(0)}%`:'Sem base anterior'}</td><td>{money(g.total)}</td></tr>)}</tbody></table></div>:<p className="planning-copy">As comparações aparecem conforme você registra seus gastos.</p>}</div>
  </>}
  <Dialog open={!!mode} onOpenChange={v=>!busy&&!v&&setMode('')}><DialogContent className="finance-dialog"><DialogTitle>{mode==='goal'?(form.id?'Editar meta':'Nova meta'):mode==='release'?'Liberar valor reservado':'Guardar para a meta'}</DialogTitle><DialogDescription>{mode==='goal'?'Informe o custo estimado e quando deseja alcançar seu objetivo.':`${form.name} · ${data.accounts.find(a=>a.id===form.account)?.name}. A ação ajusta a reserva dentro da conta, sem enviar dinheiro.`}</DialogDescription><form className="finance-form" onSubmit={submit}>
   {mode==='goal'?<><label className="field"><span>Nome do objetivo</span><input required maxLength={120} placeholder="Viagem, carro, reserva de emergência…" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Conta onde vou guardar</span><select required value={form.account||''} onChange={e=>setForm({...form,account:e.target.value})}><option value="">Selecione</option>{data.accounts.filter(a=>(scope==='GERAL'||a.scope===scope)&&(!account||a.id===account)).map(a=><option key={a.id} value={a.id}>{a.name} · {a.scope}</option>)}</select></label><div className="form-grid"><label className="field"><span>Custo total estimado (R$)</span><input required type="number" min="0.01" step="0.01" value={form.goal||''} placeholder="8000" onChange={e=>setForm({...form,goal:e.target.value})}/></label><label className="field"><span>Prazo desejado</span><input required type="date" value={form.targetDate||''} onChange={e=>setForm({...form,targetDate:e.target.value})}/></label></div><label className="field"><span>Prioridade</span><select value={form.priority||2} onChange={e=>setForm({...form,priority:Number(e.target.value)})}><option value={1}>Alta</option><option value={2}>Média</option><option value={3}>Baixa</option></select></label><label className="field"><span>Observações / custo pesquisado</span><textarea value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label></>:<><label className="field"><span>{mode==='release'?'Valor a liberar (R$)':'Valor a guardar agora (R$)'}</span><input required type="number" min="0.01" step="0.01" value={form.value??''} onChange={e=>setForm({...form,value:e.target.value})}/></label><p className="muted">{mode==='release'?`Reservado atualmente: ${money(form.amount||0)}.`:`Aporte limitado à margem da conta para os próximos ${days} dias. Reservas existentes, compromissos e rotina estimada já foram descontados.`}</p></>}
   {error&&<div role="alert" className="error">{error}</div>}<button className="btn primary full" disabled={busy}>{busy?'Salvando…':mode==='goal'?'Salvar meta':mode==='release'?'Confirmar liberação':'Confirmar reserva'}</button></form></DialogContent></Dialog>
  <AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent><AlertDialogTitle>Excluir a meta {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>O valor reservado de {money(deleting?.amount||0)} será liberado no saldo livre. O saldo bancário não muda.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={removeGoal}>Excluir e liberar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>
}
