'use client';
import {useState} from 'react';
import {ArrowLeftRight,ArrowRight,Info,ShieldCheck,Wallet} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Data,Entry,money,sum,today} from '@/lib/finance';
import {withdrawalPlan,recordWithdrawal} from '@/lib/withdrawals';

const dateLabel=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('pt-BR');
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(s:string)=>void;options:{id:string;name:string}[]}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{options.map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select></div>}
export default function WithdrawalsPanel({data,busy,save,show,onAccount}:{data:Data;busy:boolean;save:(d:Data)=>Promise<boolean>;show:(title:string,items:Entry[])=>void;onAccount:()=>void}){
 const pj=data.accounts.filter(a=>a.scope==='PJ'),pf=data.accounts.filter(a=>a.scope==='PF');
 const [source,setSource]=useState(pj[0]?.id||''),[target,setTarget]=useState(pf[0]?.id||''),[horizon,setHorizon]=useState(30),[coverage,setCoverage]=useState(1),[budget,setBudget]=useState(''),[amount,setAmount]=useState(''),[open,setOpen]=useState(false),[confirmed,setConfirmed]=useState(false),[error,setError]=useState('');
 const sourceId=pj.some(a=>a.id===source)?source:pj[0]?.id||'',targetId=pf.some(a=>a.id===target)?target:pf[0]?.id||'';
 const custom=budget===''?undefined:Math.max(0,Math.round((Number(budget)||0)*100));
 const p=withdrawalPlan(data,sourceId,targetId,horizon,coverage,custom);
 const selectedTransfers=p.transfers.filter(e=>e.destination===targetId),todayTransfers=selectedTransfers.filter(e=>(e.actual||e.date)===today());
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{if(!confirmed)throw Error('Confirme que a transferência já foi feita no banco.');const next=recordWithdrawal(data,sourceId,targetId,Math.round(Number(amount)*100),horizon,coverage,custom);if(await save(next))setOpen(false)}catch(e:any){setError(e.message)}}
 function start(){setAmount((p.suggested/100).toFixed(2));setConfirmed(false);setError('');setOpen(true)}
 if(!pj.length||!pf.length)return <div className="panel empty"><ArrowLeftRight size={30}/><strong>Conecte seu planejamento pessoal ao da empresa</strong><p>Cadastre pelo menos uma conta PJ e uma conta PF para calcular quanto pode retirar.</p><button className="btn primary" onClick={onAccount}>Cadastrar conta</button></div>;
 return <section className="planning-panel">
  <div className="section-title"><div><h2><ArrowLeftRight size={21}/> Quanto posso mandar para mim hoje?</h2><p>Escolha de onde sai, onde entra e por quanto tempo proteger a empresa.</p></div><span className="badge gray">{dateLabel(today())}</span></div>
  <div className="panel"><div className="form-grid"><Choice label="Dinheiro sai da empresa" value={sourceId} onChange={setSource} options={pj}/><Choice label="Dinheiro entra na minha conta" value={targetId} onChange={v=>{setTarget(v);setBudget('')}} options={pf}/><Choice label="Proteger compromissos da PJ" value={String(horizon)} onChange={v=>setHorizon(Number(v))} options={[7,15,30,60,90].map(n=>({id:String(n),name:`Próximos ${n} dias`}))}/><Choice label="Cobrir minha vida pessoal" value={String(coverage)} onChange={v=>setCoverage(Number(v))} options={[{id:'1',name:'Hoje'},... [7,15,30].map(n=>({id:String(n),name:`${n} dias, incluindo hoje`}))]}/></div><label className="field"><span>Orçamento de gastos do dia a dia na conta PF (R$/dia)</span><input type="number" min="0" step="0.01" placeholder={`Estimativa pelo histórico: ${(p.history.daily/100).toFixed(2)}`} value={budget} onChange={e=>setBudget(e.target.value)}/></label><p className="muted">Deixe em branco para usar a média dos registros desta conta, ou informe seu orçamento. Despesas já realizadas hoje são descontadas da necessidade de rotina. Este ajuste vale para esta simulação.</p></div>
  <div className="planning-hero"><div><span className="eyebrow">SUGESTÃO DE RETIRADA AGORA</span><strong>{money(p.suggested)}</strong><p>De {p.source?.name} para {p.target?.name}, para cobrir {coverage===1?'hoje':`até ${dateLabel(p.until)}`}.</p><button className="btn" disabled={busy||p.maximum===0} onClick={start}>Registrar transferência realizada <ArrowRight size={16}/></button></div><div className="planning-formula"><span>Falta na conta pessoal <b>{money(p.need)}</b></span><span>Máximo que esta conta PJ pode liberar <b>{money(p.maximum)}</b></span><span>Ainda faltará após a sugestão <b>{money(p.shortfall)}</b></span></div></div>
  {p.shortfall>0&&<div className="planning-warning"><strong>A margem da empresa não cobre toda a necessidade pessoal.</strong><p>Faltam {money(p.shortfall)}. Revise gastos ou vencimentos antes de retirar além da margem calculada.</p></div>}
  {p.need===0&&<p className="planning-note"><ShieldCheck size={18}/>Esta conta PF já cobre os compromissos e o orçamento do período escolhido. Não precisa receber mais agora.</p>}
  {(p.history.coverage<14||p.company.accounts.some(a=>a.coverage<14))&&<div className="planning-warning">O histórico de gastos ainda é curto em uma ou mais contas. Confira o orçamento diário e cadastre os compromissos da empresa: despesas não registradas não entram na proteção.</div>}
  <div className="two-col"><div className="panel"><h2><ShieldCheck size={20}/> O que fica protegido na empresa</h2><div className="health-line"><span>Saldo de {p.source?.name}</span><b>{money(p.source?.current||0)}</b></div><div className="health-line"><span>Reservas e metas já guardadas</span><b>− {money(p.source?.reserved||0)}</b></div><button className="health-line full" onClick={()=>show('Compromissos da conta PJ',p.source?.bills||[])}><span>Contas e faturas até {dateLabel(p.company.until)}</span><b>− {money(p.source?.committed||0)}</b></button><div className="health-line"><span>Estimativa de novos gastos da PJ</span><b>− {money(p.source?.routine||0)}</b></div><div className="health-line"><span>Falta a cobrir em outras contas PJ</span><b>− {money(p.otherGaps)}</b></div><div className="health-line"><strong>Máximo para retirar desta conta</strong><b>{money(p.maximum)}</b></div><p className="muted">A rotina usa a média dos últimos registros (até 28 dias). Valores a receber e limite de cartão não aumentam esta margem. A falta em outras contas PJ é protegida; a transferência entre essas contas continua dependendo de você.</p></div>
  <div className="panel"><h2><Wallet size={20}/> O que minha conta pessoal precisa</h2><div className="health-line"><span>Saldo atual de {p.target?.name}</span><b>{money(p.current)}</b></div><div className="health-line"><span>Reservas que não vou usar</span><b>{money(p.reserved)}</b></div><button className="health-line full" onClick={()=>show('Contas pessoais a cobrir',p.bills)}><span>Contas e faturas do período + atrasados</span><b>{money(p.committed)}</b></button><div className="health-line"><span>Rotina ainda prevista no período</span><b>{money(p.routine)}</b></div><div className="health-line"><span>Gastos cotidianos registrados hoje</span><b>{money(p.spentToday)}</b></div><div className="health-line"><strong>Precisa receber agora</strong><b>{money(p.need)}</b></div><p className="muted">Contas após {dateLabel(p.until)} não estão nesta necessidade. Aumente o período para abastecer a conta com antecedência. Reservas permanecem protegidas.</p></div></div>
  <div className="panel"><div className="section-title"><div><h2>Da empresa para {p.target?.name}</h2><p>Registrado hoje: <strong>{money(sum(todayTransfers,e=>e.amount))}</strong></p></div><button className="btn" onClick={()=>show('Histórico de retiradas PJ → PF',selectedTransfers)}>Ver histórico e editar</button></div><p className="planning-copy">O dinheiro transferido já aparece no saldo da PF e deixa de estar disponível na PJ. A sugestão é recalculada após cada registro, sem contar a retirada como nova receita ou despesa.</p></div>
  <p className="planning-note"><Info size={17}/>O Clareza calcula a margem pelos dados cadastrados e registra a movimentação. Faça a transferência no seu banco e só então confirme aqui.</p>
  <Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="finance-dialog"><DialogTitle>Registrar retirada PJ → PF</DialogTitle><DialogDescription>{p.source?.name} → {p.target?.name} · hoje, {dateLabel(today())}. Este registro atualiza os dois saldos.</DialogDescription><form className="finance-form" onSubmit={submit}><label className="field"><span>Valor transferido (R$)</span><input required type="number" min="0.01" max={p.maximum/100} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><p className="muted">Sugestão: {money(p.suggested)} · máximo neste cenário: {money(p.maximum)}.</p>{Math.round(Number(amount)*100)>p.suggested&&<p className="planning-warning">Este valor supera a necessidade pessoal calculada. O excedente permanecerá na sua conta PF.</p>}<label className="planning-note"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>Já fiz esta transferência no banco hoje.</label>{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy||!confirmed}>{busy?'Salvando…':'Confirmar registro'}</button></form></DialogContent></Dialog>
 </section>;
}
