export type Account={id:string;name:string;institution:string;scope:string;initial:number};
export type Card={id:string;name:string;scope:string;limit:number;closing:number;due:number;account:string};
export type Entry={id:string;description:string;amount:number;date:string;scope:string;account:string;destination?:string;kind:string;method:string;status:string;category:string;subcategory?:string;origin?:string;notes?:string;card?:string;invoice?:string;part?:string;group?:string;actual?:string;receipt?:string;recurrence?:string;originalAmount?:number;debtId?:string};
export type Reserve={id:string;name:string;account:string;amount:number;goal:number;isGoal?:boolean;targetDate?:string;priority?:number;notes?:string};
export type Data={accounts:Account[];cards:Card[];entries:Entry[];reserves:Reserve[];categories:string[]};
export const empty:Data={accounts:[],cards:[],entries:[],reserves:[],categories:['Moradia','Alimentação','iFood','Transporte','Faculdade','Energia','Água','Internet','Academia','Pets','Roupas','Lazer','Saúde','Dívidas e empréstimos','Clientes','Funcionários','Marketing','Tráfego','Softwares','Infraestrutura','Equipamentos','Fornecedores','Impostos','Serviços','Comissões']};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function addDays(d:string,n:number){const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10)}
export function addMonths(d:string,n:number){const x=new Date(d+'T12:00:00Z'),day=x.getUTCDate();x.setUTCDate(1);x.setUTCMonth(x.getUTCMonth()+n);x.setUTCDate(Math.min(day,new Date(Date.UTC(x.getUTCFullYear(),x.getUTCMonth()+1,0)).getUTCDate()));return x.toISOString().slice(0,10)}
export const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n/100);
export const sum=(a:any[],f:(x:any)=>number)=>a.reduce((s,x)=>s+f(x),0);
export function validDate(date:string){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&!Number.isNaN(Date.parse(date+'T12:00:00Z'))&&new Date(date+'T12:00:00Z').toISOString().slice(0,10)===date}

export function settleDebt(data:Data,id:string,amount:number,account:string,actual:string,nextDate?:string):Data{
 const d=structuredClone(data),debt=d.entries.find(e=>e.id===id),bank=d.accounts.find(a=>a.id===account);
 if(!debt||debt.kind!=='expense'||debt.card||debt.status!=='pending'||debt.debtId)throw Error('Esta conta não está disponível para pagamento.');
 if(!bank||bank.scope!==debt.scope)throw Error('Escolha uma conta do mesmo tipo PF/PJ da dívida.');
 if(!Number.isSafeInteger(amount)||amount<=0||amount>debt.amount)throw Error('Informe um valor positivo, até o saldo restante da dívida.');
 if(!validDate(actual)||actual>today())throw Error('Informe uma data real de pagamento válida.');
 if(amount<debt.amount&&(!nextDate||!validDate(nextDate)||nextDate<actual))throw Error('Informe o vencimento do restante, a partir da data do pagamento.');
 debt.originalAmount=debt.originalAmount||debt.amount;
 if(amount===debt.amount){debt.status='paid';debt.account=account;debt.actual=actual;}
 else{
  d.entries.push({id:crypto.randomUUID(),debtId:debt.id,description:'Pagamento parcial · '+debt.description,amount,date:actual,actual,scope:debt.scope,account,kind:'expense',method:debt.method,status:'paid',category:debt.category,subcategory:debt.subcategory,notes:'Abatimento da dívida. Saldo restante no lançamento original.'});
  debt.amount-=amount;debt.date=nextDate!;
 }
 validate(d);return d;
}

export function validatePlanningRecords(d:Data){
 if(!Array.isArray(d.entries)||!Array.isArray(d.reserves))throw Error('Dados financeiros inválidos');
 for(const e of d.entries){
  if(e.debtId){const parent=d.entries.find(p=>p.id===e.debtId);if(!parent||!parent.originalAmount||parent.debtId||e.kind!=='expense'||e.card||e.status!=='paid'||parent.scope!==e.scope)throw Error('Pagamento parcial sem vínculo válido.');}
  if(e.originalAmount!==undefined){if(!Number.isSafeInteger(e.originalAmount)||e.originalAmount<=0||e.kind!=='expense'||e.card||!['paid','pending'].includes(e.status)||e.amount+sum(d.entries.filter(p=>p.debtId===e.id),p=>p.amount)!==e.originalAmount)throw Error('O total da dívida deve corresponder aos pagamentos e ao saldo restante.');}
 }
 for(const r of d.reserves){if(r.isGoal&&(!r.name?.trim()||!Number.isSafeInteger(r.goal)||r.goal<=0||r.amount>r.goal||!r.targetDate||!validDate(r.targetDate)||![1,2,3].includes(r.priority||2)))throw Error('Revise o valor, o prazo e a prioridade da meta.');}
}
export function relative(d:string){const n=Math.round((Date.parse(d)-Date.parse(today()))/86400000);return n===0?'Hoje':n===1?'Amanhã':n<0?`Atrasado há ${-n} dias`:`Em ${n} dias`}
export function balance(d:Data,id:string){return (d.accounts.find(a=>a.id===id)?.initial||0)+sum(d.entries.filter(e=>e.status==='paid'),e=>e.kind==='transfer'?(e.destination===id?e.amount:0)-(e.account===id?e.amount:0):e.account!==id?0:e.kind==='income'?e.amount:e.kind==='invoice'||(e.kind==='expense'&&!e.card)?-e.amount:0)}
export function invoiceDate(date:string,c:Card){const closing=date.slice(0,8)+String(Math.min(c.closing,new Date(+date.slice(0,4),+date.slice(5,7),0).getDate())).padStart(2,'0');let month=date.slice(0,8)+'01';if(date>=closing)month=addMonths(month,1);if(c.due<=c.closing)month=addMonths(month,1);return month.slice(0,8)+String(Math.min(c.due,new Date(+month.slice(0,4),+month.slice(5,7),0).getDate())).padStart(2,'0')}

export function invoices(d:Data){const map=new Map<string,Entry>();for(const e of d.entries.filter(e=>e.card&&e.kind==='expense'&&e.status!=='cancelled')){const id=e.card+':'+e.invoice;if(!map.has(id)){const c=d.cards.find(c=>c.id===e.card)!;map.set(id,{id,description:'Fatura '+c.name,amount:0,date:e.invoice!,scope:c.scope,account:c.account,kind:'invoice',method:'Transferência',status:'pending',category:'Fatura',card:c.id,invoice:e.invoice})}map.get(id)!.amount+=e.amount}return [...map.values()].map(e=>({...e,amount:e.amount-sum(d.entries.filter(p=>p.kind==='invoice'&&p.card===e.card&&p.invoice===e.invoice&&p.status==='paid'),p=>p.amount)})).filter(e=>e.amount>0)}
export function obligations(d:Data){return [...d.entries.filter(e=>e.kind==='expense'&&!e.card&&e.status==='pending'),...invoices(d)]}
export function metrics(d:Data,scope:string,account:string,days:number){const ids=d.accounts.filter(a=>(scope==='GERAL'||a.scope===scope)&&(!account||a.id===account)).map(a=>a.id),end=addDays(today(),days);const matches=(e:Entry)=>(scope==='GERAL'||e.scope===scope)&&(!account||e.account===account);const current=sum(ids,id=>balance(d,id));const reserved=sum(d.reserves.filter(r=>ids.includes(r.account)),r=>r.amount);const owed=obligations(d).filter(e=>matches(e)&&e.date<=end);const incoming=d.entries.filter(e=>e.kind==='income'&&e.status==='pending'&&matches(e));const committed=sum(owed,e=>e.amount);const rows=[];let withIncome=current,without=current;for(let i=0;i<=90;i++){const date=addDays(today(),i);const due=obligations(d).filter(e=>matches(e)&&(i===0?e.date<=date:e.date===date));const inc=incoming.filter(e=>i===0?e.date<=date:e.date===date);without-=sum(due,e=>e.amount);withIncome+=sum(inc,e=>e.amount)-sum(due,e=>e.amount);rows.push({date,label:date.slice(8)+'/'+date.slice(5,7),withIncome,without,incoming:sum(inc,e=>e.amount),outgoing:sum(due,e=>e.amount),items:[...inc,...due]})}return {current,reserved,committed,free:current-reserved-committed,owed,incoming,rows,projected:rows[days].withIncome}}
export function validate(d:Data){
validatePlanningRecords(d);
for(const key of ['accounts','cards','entries','reserves','categories'])if(!Array.isArray((d as any)[key]))throw Error('Estrutura inválida');
for(const key of ['accounts','cards','entries','reserves']){const list=(d as any)[key];if(new Set(list.map((x:any)=>x.id)).size!==list.length)throw Error('Identificadores duplicados');}
for(const e of d.entries){if(!['income','expense','transfer','invoice'].includes(e.kind)||!['paid','pending','cancelled'].includes(e.status))throw Error('Tipo ou situação inválidos');if(e.scope!==d.accounts.find(a=>a.id===e.account)?.scope&&e.kind!=='invoice')throw Error('Tipo PF/PJ deve corresponder à conta');if(e.status==='paid'&&(e.actual||e.date)>today())throw Error('Data de quitação não pode ser futura');if(e.kind==='transfer'&&e.status!=='paid')throw Error('Transferência deve ser efetivada');if(e.card&&e.kind==='expense'&&(!e.invoice||!/^\d{4}-\d{2}-\d{2}$/.test(e.invoice)))throw Error('Vencimento da fatura inválido');}
for(const c of d.cards){if(!Number.isSafeInteger(c.limit)||!Number.isInteger(c.closing)||!Number.isInteger(c.due)||!c.name||c.scope!==d.accounts.find(a=>a.id===c.account)?.scope)throw Error('Revise o cartão e a conta PF/PJ de pagamento');}
const billKeys=new Set(d.entries.filter(e=>e.card).map(e=>e.card+':'+e.invoice));for(const key of billKeys){const list=d.entries.filter(e=>e.card+':'+e.invoice===key&&e.status!=='cancelled');if(sum(list.filter(e=>e.kind==='invoice'&&e.status==='paid'),e=>e.amount)>sum(list.filter(e=>e.kind==='expense'),e=>e.amount))throw Error('O pagamento excede o total da fatura');}
const ids=new Set(d.accounts.map(a=>a.id));for(const a of d.accounts)if(!a.name||!Number.isSafeInteger(a.initial)||!['PF','PJ'].includes(a.scope))throw Error('Conta inválida');for(const c of d.cards)if(!ids.has(c.account)||c.limit<0||c.closing<1||c.closing>31||c.due<1||c.due>31)throw Error('Cartão inválido. Fechamento: 1 a 31; vencimento: 1 a 31.');for(const e of d.entries){if(!ids.has(e.account)||!e.description||!Number.isSafeInteger(e.amount)||e.amount<=0||!/^\d{4}-\d{2}-\d{2}$/.test(e.date))throw Error('Revise os dados do lançamento');if(e.kind==='transfer'&&(!ids.has(e.destination!)||e.destination===e.account))throw Error('Selecione uma conta de destino diferente');if(e.card&&!d.cards.some(c=>c.id===e.card))throw Error('Cartão não encontrado')}for(const r of d.reserves)if(!ids.has(r.account)||r.amount<0||!Number.isSafeInteger(r.amount))throw Error('Reserva inválida');for(const a of d.accounts)if(sum(d.reserves.filter(r=>r.account===a.id),r=>r.amount)>Math.max(0,balance(d,a.id)))throw Error('As reservas excedem o saldo da conta. Libere a reserva antes de usar esse dinheiro.');for(const c of d.cards)if(sum(invoices(d).filter(i=>i.card===c.id),i=>i.amount)>c.limit)throw Error('Compra excede o limite disponível do cartão')}
export function financialHistory(d:Data,scope:string,account:string){const rows=[];for(let i=5;i>=0;i--){const month=addMonths(today().slice(0,7)+'-01',-i).slice(0,7);const end=addDays(addMonths(month+'-01',1),-1);const selected=d.accounts.filter(a=>(scope==='GERAL'||a.scope===scope)&&(!account||a.id===account));const e=d.entries.filter(e=>(scope==='GERAL'||e.scope===scope)&&(!account||e.account===account)&&e.status!=='cancelled');const real=e.filter(e=>(e.actual||e.date).startsWith(month));rows.push({month,label:new Date(month+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'short'}),income:sum(real.filter(e=>e.kind==='income'&&e.status==='paid'),e=>e.amount),expense:sum(real.filter(e=>e.kind==='expense'&&(e.status==='paid'||e.card)),e=>e.amount),balance:sum(selected,a=>balance({...d,entries:d.entries.filter(e=>(e.actual||e.date)<=end)},a.id))})}return rows}
